#!/usr/bin/node

let fs = require("fs");
let Phrase = require("thomas-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line){
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log("palindrome detected:", line);
  }
})

let write = fs.writeFile("palindrome.txt", text, function (err) {
  if (err) return console.log(err);
  console.log('The file was saved');
});
